version: '3.5'
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.87,nolock,soft,rw"
      device: ":/mnt/data/grafana"
services:
  software:
    image: grafana/grafana
    networks:
      - internal
#   environment:
#     - GF_INSTALL_PLUGINS='grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - data:/var/lib/grafana
    secrets:
      - source: grafana_env
        target: /conf/custom.ini 
        mode: 0666
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: "grafana"
        traefik.docker.network: "internal"
        traefik.frontend.rule: "Host:grafana.leejonchapman.com"
        traefik.web.port: "3000"
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.SSLHost: "grafana.leejonchapman.com"
      placement:
        constraints:
          - node.role == worker
      mode: global
      restart_policy:
        condition: any
        max_attempts: 3
secrets:
  grafana_env:
    file: ./grafana.env
networks:
  internal:
    name: internal
    external: true



